// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjDGKmnqHA4j66YaWLxQ3ryyzHcNsvfM',
    appId: '1:680568476111:web:a23cc46d1aa49b160982ba',
    messagingSenderId: '680568476111',
    projectId: 'food-delivery-c2741',
    authDomain: 'food-delivery-c2741.firebaseapp.com',
    storageBucket: 'food-delivery-c2741.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt34pO6GbdYE1Ij6g4oq6LsMDeO3qmdac',
    appId: '1:680568476111:android:c3e1907a4002e8610982ba',
    messagingSenderId: '680568476111',
    projectId: 'food-delivery-c2741',
    storageBucket: 'food-delivery-c2741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxSABb1jJK3-uhxwZ859efktVCN-qeSk',
    appId: '1:680568476111:ios:0bf3d68836cb30450982ba',
    messagingSenderId: '680568476111',
    projectId: 'food-delivery-c2741',
    storageBucket: 'food-delivery-c2741.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuxSABb1jJK3-uhxwZ859efktVCN-qeSk',
    appId: '1:680568476111:ios:0bf3d68836cb30450982ba',
    messagingSenderId: '680568476111',
    projectId: 'food-delivery-c2741',
    storageBucket: 'food-delivery-c2741.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEjDGKmnqHA4j66YaWLxQ3ryyzHcNsvfM',
    appId: '1:680568476111:web:5feff77d8e1562510982ba',
    messagingSenderId: '680568476111',
    projectId: 'food-delivery-c2741',
    authDomain: 'food-delivery-c2741.firebaseapp.com',
    storageBucket: 'food-delivery-c2741.appspot.com',
  );
}
